
services:
  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8787
    volumes:
      - ../../apps/web:/app
      - web_node_modules:/app/node_modules
      - web_next:/app/.next
    command: npm run dev
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.dev
    ports:
      - "8787:8787"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - PORT=8787
      - DATA_DIR=/app/data
      - TEMP_DIR=/app/temp
      - GCP_PROJECT_ID=one-to-multi-agent-80339
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=one_to_multi_agent
      - DB_PORT=5432
    volumes:
      - ../../apps/api:/app
      - api_node_modules:/app/node_modules
      - api_data:/app/data
      - api_temp:/app/temp
      - ../../gcp-service-account-key.json:/app/gcp-service-account-key.json:ro
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  # Database (PostgreSQL for both development and production)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: one_to_multi_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql/create-metadata-tables.sql:/docker-entrypoint-initdb.d/01-create-metadata-tables.sql
      - ./init-db.sql:/docker-entrypoint-initdb.d/02-init-db.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for job queuing and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    profiles:
      - production

  # File storage (MinIO as S3-compatible storage for development)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    profiles:
      - storage

volumes:
  web_node_modules:
  web_next:
  api_node_modules:
  api_data:
  api_temp:
  postgres_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge