
services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8787
    volumes:
      - ../../apps/web:/app/apps/web
      - ../../packages:/app/packages
      - ../../package.json:/app/package.json
      - ../../package-lock.json:/app/package-lock.json
      - web_node_modules:/app/node_modules
      - web_app_node_modules:/app/apps/web/node_modules
      - web_next:/app/apps/web/.next
    working_dir: /app/apps/web
    command: npm run dev
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile.dev
    ports:
      - "8787:8787"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - PORT=8787
      - DATA_DIR=/app/apps/api/data
      - TEMP_DIR=/app/apps/api/temp
      - STORAGE_DIR=/app/apps/api/storage
      - GCP_PROJECT_ID=one-to-multi-agent
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=one_to_multi_agent
      - DB_PORT=5432
    volumes:
      - ../../apps/api:/app/apps/api
      - ../../packages:/app/packages
      - ../../package.json:/app/package.json
      - ../../package-lock.json:/app/package-lock.json
      - api_node_modules:/app/node_modules
      - api_app_node_modules:/app/apps/api/node_modules
      - api_data:/app/apps/api/data
      - api_temp:/app/apps/api/temp
      - api_storage:/app/apps/api/storage
      - ../../gcp-service-account-key.json:/app/gcp-service-account-key.json:ro
    working_dir: /app/apps/api
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  # Database (PostgreSQL for both development and production)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: one_to_multi_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql/create-metadata-tables.sql:/docker-entrypoint-initdb.d/01-create-metadata-tables.sql
      - ../sql/add-original-file-columns.sql:/docker-entrypoint-initdb.d/02-add-original-file-columns.sql
      - ./init-db.sql:/docker-entrypoint-initdb.d/03-init-db.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Redis for job queuing and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    profiles:
      - production


volumes:
  web_node_modules:
  web_app_node_modules:
  web_next:
  api_node_modules:
  api_app_node_modules:
  api_data:
  api_temp:
  api_storage:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge